EXAMPLES_BASE	?= c:/Espressif/examples/ESP8266

# Main settings includes
include	$(EXAMPLES_BASE)/settings.mk

# Individual project settings (Optional)
#BOOT		= new
#APP		= 1
#SPI_SPEED	= 40
#SPI_MODE	= QIO
#SPI_SIZE_MAP	= 2
#ESPPORT		= COM2
#ESPBAUD		= 256000

# Root includes
include	$(EXAMPLES_BASE)/common_nonos_app.mk
