#ifndef __USER_CONFIG_H__
#define __USER_CONFIG_H__

#define DEBUG_LEVEL			3

#define USE_WIFI_MODE		STATIONAP_MODE
#define WIFI_CLIENTSSID		"ESP8266-AP"
#define WIFI_CLIENTPASSWORD	"1234567890"
#define WIFI_AP_NAME		"ESP8266"
#define WIFI_AP_PASSWORD	"00000000"

#endif
