#ifndef __USER_CONFIG_H__
#define __USER_CONFIG_H__

#define USE_WIFI_MODE		STATIONAP_MODE
#define WIFI_CLIENTSSID		"MYAP"
#define WIFI_CLIENTPASSWORD	"00000000"
#define WIFI_AP_NAME		"ESP8266"
#define WIFI_AP_PASSWORD	"00000000"
#define TCPSERVERIP		"192.168.1.100"
#define TCPSERVERPORT		5555
#define PLATFORM_DEBUG		true
//#define LWIP_DEBUG		true

#endif
